# 1. Port (Nhận biến môi trường PORT từ Cloud Provider, mặc định 8080)
server.port=${PORT:8080}

# 2. Database Connection (Sử dụng biến môi trường khi lên Cloud)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iot_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:duc_password_123}

# 3. Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4. Disable auto SQL init
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.thymeleaf.cache=false

# 5. MQTT Broker Configuration (Ưu tiên biến môi trường)
# HiveMQ Cloud - cùng broker với ESP32 firmware
mqtt.broker.url=${MQTT_BROKER_URL:ssl://10cf23427b77452faec8dc86e09f1bc1.s1.eu.hivemq.cloud:8883}
mqtt.username=${MQTT_USERNAME:tienduc}
mqtt.password=${MQTT_PASSWORD:D@ucffgh123}
mqtt.topic.sensor=iot/sensor/data/+
mqtt.topic.command-status=iot/device/control-status/+
