

services:
  # Service 1: Cơ sở dữ liệu PostgreSQL
  db-web-iot:
    image: postgres:15
    container_name: postgres-iot-web
    restart: always
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duc_password_123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"  
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Service 2: Ứng dụng Java (Tạm thời để trống để build sau)
  java-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: iot-java-service
    ports:
      - "8081:8080"
    depends_on:
      - db-web-iot
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-web-iot:5432/iot_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=duc_password_123
      - MQTT_BROKER_URL=ssl://10cf23427b77452faec8dc86e09f1bc1.s1.eu.hivemq.cloud:8883
      - MQTT_USERNAME=tienduc
      - MQTT_PASSWORD=D@ucffgh123

  # Service 3: MQTT Broker (Mosquitto)
  mosquitto-iot-web:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-iot-web
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
